## **1. Introduction to Pytorch**

In [1]:
import torch

## **2. Perform all linear algebra operation with Tensorflow.**

In [ ]:
A = torch.randn(3,3)
B = torch.randn(3,3)
C = torch.randn(3)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C:\n", C)

Matrix A:
 tensor([[ 0.0143,  1.0173, -0.7016],
        [ 0.5778, -1.1316, -1.8148],
        [-1.5649, -1.4517, -0.4961]])
Matrix B:
 tensor([[-1.0442,  0.4624, -0.2444],
        [-0.6071,  0.3394, -1.5578],
        [-0.1598,  0.3706, -2.3345]])
Matrix C:
 tensor([-1.1186, -0.3451, -0.8979])


In [ ]:
# Aritmetic Operations
print("A + B = \n", A + B)
print("A - B = \n", A - B)

A + B = 
 tensor([[-1.0299,  1.4797, -0.9460],
        [-0.0293, -0.7921, -3.3726],
        [-1.7247, -1.0811, -2.8306]])
A - B = 
 tensor([[ 1.0585,  0.5549, -0.4572],
        [ 1.1848, -1.4710, -0.2569],
        [-1.4051, -1.8223,  1.8384]])


In [ ]:
# Broadcasting
print("A + C =\n", A + C)

A + C =
 tensor([[-1.1043,  0.6722, -1.5995],
        [-0.5408, -1.4767, -2.7127],
        [-2.6835, -1.7968, -1.3940]])


In [ ]:
# Scalar Multiplication
print("A * 2 =\n", A * 2)

A * 2 =
 tensor([[ 0.0286,  2.0346, -1.4031],
        [ 1.1556, -2.2631, -3.6295],
        [-3.1299, -2.9034, -0.9922]])


In [ ]:
# Element wise Multiplication
print("A * B =\n", A * B)

A * B =
 tensor([[-0.0149,  0.4704,  0.1715],
        [-0.3507, -0.3841,  2.8271],
        [ 0.2501, -0.5380,  1.1582]])


In [ ]:
# Matrix Multiplication
print("A @ B =\n", A @ B)

A @ B =
 tensor([[-0.5204,  0.0919,  0.0495],
        [ 0.3736, -0.7894,  5.8581],
        [ 2.5947, -1.4002,  3.8022]])


In [ ]:
# Tanspose
print("A transpose:\n",A.T)

A transpose:
 tensor([[ 0.0143,  0.5778, -1.5649],
        [ 1.0173, -1.1316, -1.4517],
        [-0.7016, -1.8148, -0.4961]])


## **3. Write a program to implement AND OR gates using Perceptron.**

In [ ]:
class Perceptron:
  def __init__(self, input_size, lr=0.1):
    self.weights = torch.zeros(input_size)
    self.bais = 0.0
    self.lr = lr

  def activation(self, x):
    return 1 if x >= 0 else 0

  def predict(self, x):
    x = torch.tensor(x, dtype=torch.float32)
    linear_output = torch.dot(self.weights, x) + self.bais
    return self.activation(linear_output)

  def train(self, x, y, epochs=20):
    for _ in range(epochs):
      for xi, target in zip(x, y):
        xi = torch.tensor(xi, dtype=torch.float32)
        output = self.predict(xi)
        error = target - output

        self.weights += self.lr * error * xi
        self.bais += self.lr * error

In [ ]:
def gate(name, x, y):
  print(f"\nTrainig Perceptron for {name} Gate:")
  p = Perceptron(input_size=2, lr=0.1)
  p.train(x, y, epochs=20)

  print(f"Weights: {p.weights}")
  print(f"Bias: {p.bais}")

  print(f"\n{name} Gate Truth Table Prediction:")
  for xi in x:
      print(f"{xi} -> {p.predict(xi)}")

In [ ]:
x = [
    [0,0],
    [0,1],
    [1,0],
    [1,1]
]

y_and = [0, 0, 0, 1]
y_or = [0, 1, 1, 1]

In [ ]:
gate("AND", x, y_and)


Trainig Perceptron for AND Gate:
Weights: tensor([0.2000, 0.1000])
Bias: -0.30000000000000004

AND Gate Truth Table Prediction:
[0, 0] -> 0
[0, 1] -> 0
[1, 0] -> 0
[1, 1] -> 1


/tmp/ipython-input-879634657.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32)


In [ ]:
gate("OR", x, y_or)


Trainig Perceptron for OR Gate:
Weights: tensor([0.1000, 0.1000])
Bias: -0.1

OR Gate Truth Table Prediction:
[0, 0] -> 0
[0, 1] -> 1
[1, 0] -> 1
[1, 1] -> 1


/tmp/ipython-input-879634657.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32)


## **4. Implementation of XOR Problem using PyTorch Neural Network.**

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# XOR Dataset
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

# Neural Network Model
class XORNet(nn.Module):# nn.Module is the base class for all neural network modules in PyTorch
    def __init__(self):
        super(XORNet, self).__init__()
        self.fc1 = nn.Linear(2, 2)  # Input to hidden layer
        self.fc2 = nn.Linear(2, 1)   # Hidden to output layer
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.sigmoid(self.fc1(x))
        x = self.sigmoid(self.fc2(x))
        return x

In [ ]:
# Training
model = XORNet()

criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9)

epochs = 10000
for epoch in range(epochs):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print progress
    if (epoch+1) % 1000 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [1000/10000], Loss: 0.2247
Epoch [2000/10000], Loss: 0.0096
Epoch [3000/10000], Loss: 0.0047
Epoch [4000/10000], Loss: 0.0031
Epoch [5000/10000], Loss: 0.0023
Epoch [6000/10000], Loss: 0.0019
Epoch [7000/10000], Loss: 0.0016
Epoch [8000/10000], Loss: 0.0013
Epoch [9000/10000], Loss: 0.0012
Epoch [10000/10000], Loss: 0.0010


In [ ]:
# Evaluation
with torch.no_grad():
    predictions = model(X)
    predicted_labels = (predictions > 0.5).float()
    accuracy = (predicted_labels == y).float().mean()

    print("\nFinal Predictions:")
    for i in range(len(X)):
        print(f"Input: {X[i].tolist()}, Predicted: {predictions[i].item():.4f}, Target: {y[i].item()}")

    print(f"\nAccuracy: {accuracy.item()*100:.2f}%")


Final Predictions:
Input: [0.0, 0.0], Predicted: 0.0012, Target: 0.0
Input: [0.0, 1.0], Predicted: 0.9991, Target: 1.0
Input: [1.0, 0.0], Predicted: 0.9991, Target: 1.0
Input: [1.0, 1.0], Predicted: 0.0011, Target: 0.0

Accuracy: 100.00%


## **5. Implement Simple below Neural Network to solve regression problem.**

In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv('/content/house_price_full+(2) - house_price_full+(2).csv')

x = df[['bedrooms', 'sqft_living']].values.astype('float32')
y = df[['price']].values.astype('float32')

print(type(x))

<class 'numpy.ndarray'>


In [5]:
scaler_x = StandardScaler()
scaler_y = StandardScaler()

In [6]:
x_scaled = scaler_x.fit_transform(x)
y_scaled = scaler_y.fit_transform(y)

In [7]:
x_t = torch.tensor(x_scaled, dtype=torch.float32)
y_t = torch.tensor(y_scaled, dtype=torch.float32)

In [8]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(2, 2),
            nn.ReLU(),
            nn.Linear(2, 1)
        )
    def forward(self, x):
        return self.net(x)

model = Model()

In [9]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [10]:
epochs = 20000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(x_t)
    loss = criterion(outputs, y_t)
    loss.backward()
    optimizer.step()

    if epoch % 5000 == 0:
        print("Epoch", epoch, "Loss:", loss.item())

Epoch 0 Loss: 1.3515430688858032
Epoch 5000 Loss: 0.49837741255760193
Epoch 10000 Loss: 0.4983743131160736
Epoch 15000 Loss: 0.4983721673488617


In [11]:
# Predictions
pred_scaled = model(x_t).detach().numpy()
pred_real = scaler_y.inverse_transform(pred_scaled)

for i in range(10):
    print(f"Input: {x[i]} => Predicted: {pred_real[i][0]:.2f}, Target: {y[i][0]:.2f}")

Input: [   3. 1340.] => Predicted: 356481.50, Target: 313000.00
Input: [   5. 3650.] => Predicted: 924443.38, Target: 2384000.00
Input: [   3. 1930.] => Predicted: 491770.91, Target: 342000.00
Input: [   3. 2000.] => Predicted: 509324.06, Target: 420000.00
Input: [   4. 1940.] => Predicted: 465888.59, Target: 550000.00
Input: [  2. 880.] => Predicted: 356481.50, Target: 490000.00
Input: [   2. 1350.] => Predicted: 394133.47, Target: 335000.00
Input: [   4. 2710.] => Predicted: 654969.25, Target: 482000.00
Input: [   3. 2430.] => Predicted: 617150.56, Target: 452500.00
Input: [   4. 1520.] => Predicted: 378078.56, Target: 640000.00
